### ISSUE TITLE
Can't get menu inside getStaticProps in index.js

### ISSUE THREAD

**Issue by je34429** [chapter-three/next-drupal#17]
First of all, great module!

so far I've configured the module without much trouble to fetch content types and get dynamic aliases with pathauto, but when I try running this on my index.js (I'm using js instead of ts):
`const { tree, items } = await getMenu("main")`
`console.log('items',items);`
I get a not found error, and I'm sure the menu exists inside drupal and that its machine name is main so I'm not sure if I have to configure some entity or do something apart from fetching with your function:
`Error: Not Found
    at /gitlab/drupalnext/node_modules/next-drupal/dist/index.js:169:17
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getStaticProps (webpack-internal:///./pages/index.js:72:7)
    at async renderToHTML (/gitlab/drupalnext/node_modules/next/dist/next-server/server/render.js:27:1780)
    at async /gitlab/drupalnext/node_modules/next/dist/next-server/server/next-server.js:112:97
    at async __wrapper (/gitlab/drupalnext/node_modules/next/dist/lib/coalesced-function.js:1:330)
    at async DevServer.renderToHTMLWithComponents (/gitlab/drupalnext/node_modules/next/dist/next-server/server/next-server.js:137:387)
    at async DevServer.renderToHTML (/gitlab/drupalnext/node_modules/next/dist/next-server/server/next-server.js:138:610)
    at async DevServer.renderToHTML (/gitlab/drupalnext/node_modules/next/dist/server/next-dev-server.js:36:578)`

any help will be highly appreciated.

Best regards

**Comment by arshad** [comment]
Do you have the https://www.drupal.org/project/jsonapi_menu_items module installed? 

I’ll need to update the docs.

**Comment by je34429** [comment]
installing the module solved the problem

thanks a lot!
