### ISSUE TITLE
FetchError 😢  reason: getaddrinfo ENOTFOUND 

### ISSUE THREAD

**Issue by 42zeroo** [chapter-three/next-drupal#24]
Hi! Thanks for publish this awesome project 🗡️

 I wanted to try combination of Drupal + NextJS but i have problem when I'm initializing your example project following the [Instruction here](https://next-drupal.org/docs/quick-start). 
After i did all the steps, i recived error from Next.JS: 
![Screen1NEXTJSCONSOLE](https://user-images.githubusercontent.com/29521242/136642102-97999c9f-b62e-4192-b88f-e7e4063744a1.png)

I'm using wodby/docker4drupal docker image, but i tried on XAMPP environment too, and on XAMPP i had a bit different error:
 ``` Error: Not Found 
35| export async function getStaticProps(context) { const articles = await getResourceCollectionFromContext(
    |                                                                  ^
34| "node--article", 
 ``` 
 
As I undestood my connection between Drupal and Next.JS should be estabished well. I provided ``DRUPAL_CLIENT_ID`` and ``DRUPAL_CLIENT_SECRET`` in _.env.local_ file. I also tried with ``NODE_TLS_REJECT_UNAUTHORIZED=0`` flag.
 I followed all the steps from tutorial couple of times with same result every time. What could be the problem? Sorry, i'm new with decoupling Drupal.
 
 I will appreciate all your help! 😄

**Comment by 42zeroo** [comment]
Thanks for your reply!
Ofc, i can reach ``http://drupal.docker.localhost:8000`` and when i open ``/jsonapi`` i recived normal Drupal JSON Api structure, [what i got is here](https://pastebin.com/uEZHyJgH).

Also when i want to look into preview on Drupal side i have the same error.
![Error](https://user-images.githubusercontent.com/29521242/136661742-9a87dc77-dc91-47c4-a0d6-3bfcf7ed44d7.png)

I added my drupal domain to .host file. I disabled firewall and antyvirus, still same error.

**Comment by 42zeroo** [comment]
I'm not familliar with Drupal auth api. Can You advice me how to do it? 😶 
Do I have to enable anything more after setting up project from tutorial?

**Comment by demo-Ghost** [comment]
Hi! Did you check the video tutorials here https://www.drupal.org/project/simple_oauth?
Check the password grant type tutorial.

Apparently, you have to first send a POST request to
[Drupal Base URL]/oauth/token
like this (in Postman):
![image](https://user-images.githubusercontent.com/37753045/137379515-1055d583-0bea-49f7-b723-576f9fa0a500.png)

And then, if you have debug token permissions from Drupal enabled, you cna also check if the token works properly by making a GET request to [Drupal Base URL]/oauth/debug?_format=json, with only one Header necessarily configured:
![image](https://user-images.githubusercontent.com/37753045/137379717-b38f797e-4a85-4d5f-b6e4-6a5c23210a91.png)

**Comment by 42zeroo** [comment]
Finally after few attempts i went forwards 👯 
And I achived... new error 🥇 
![image](https://user-images.githubusercontent.com/29521242/137649767-29e9f93b-faa5-4d24-a8c4-6a9d967853a0.png)
`> Build error occurred
Error: Not Found
    at C:\PROJEKTY\reccly-dev-drupal\node_modules\next-drupal\dist\index.js:23:15
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Promise.all (index 1)
    at async getStaticPaths (C:\PROJEKTY\reccly-dev-drupal\.next\server\pages\[...slug].js:112:12)
    at async buildStaticPaths (C:\PROJEKTY\reccly-dev-drupal\node_modules\next\dist\build\utils.js:472:31)
    at async C:\PROJEKTY\reccly-dev-drupal\node_modules\next\dist\build\utils.js:615:119
    at async Span.traceAsyncFn (C:\PROJEKTY\reccly-dev-drupal\node_modules\next\dist\telemetry\trace\trace.js:60:20) {
  type: 'Error'
}
`
I tried to find any solution on google but i dont have much info describing error :/

**Comment by shadcn** [comment]
Hmm it looks like it still cannot find your Drupal site. Weird. Can you remove `DRUPAL_CLIENT_ID` and `DRUPAL_CLIENT_SECRET` from your `.env.local` file and try again?

This will skip auth and token generation.
