### ISSUE TITLE
npn run dev not working as expected, throwing an error

### ISSUE THREAD

**Issue by kanchamk** [chapter-three/next-drupal#261]
![Nextjs error](https://user-images.githubusercontent.com/34206567/179179502-78cfa64f-ecb1-4f03-a1b1-cb68f691102c.PNG)

I followed the steps mentioned in this url https://next-drupal.org/learn/quick-start/create-nexts-project. but getting below error.

`D:\Sites\drupal_demo\next\node_modules\next\dist\trace\report\index.js:14
    reporters = [];
              ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\Sites\drupal_demo\next\node_modules\next\dist\trace\trace.js:6:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
`

**Comment by shadcn** [comment]
hmm not sure what's happening here. I don't have a Windows machine to try and debug this either.

Can you check if you can reproduce this error using a vanilla Next.js: `npx create-next-app`?

**Comment by o771e** [comment]
When you run "npx create-next-app" what app name do you use?

**Comment by kanchamk** [comment]
I used **next_drupal**,  **next**, **drupal_next** as app name, do I need to follow any naming conventions?

**Comment by kanchamk** [comment]
Working fine now after hours of debugging
Fix: Upgraded my node version to its latest i.e 16
