### ISSUE TITLE
Won't build in Vercel, or manually.

### ISSUE THREAD

**Issue by engageintellect** [chapter-three/next-drupal#366]
Love this template, and would like to use it for a personal project. Just noticed it's not building using the Vercel deploy option, or locally building.

Here's the output from vercel.
```
[10:10:22.008] Cloning github.com/engageintellect/drupal-nextjs-marketing (Branch: main, Commit: e436508)
[10:10:22.306] Previous build cache not available
[10:10:22.668] Cloning completed: 659.61ms
[10:10:23.085] Running "vercel build"
[10:10:23.591] Vercel CLI 28.5.6
[10:10:23.900] Installing dependencies...
[10:10:24.271] yarn install v1.22.17
[10:10:24.291] info No lockfile found.
[10:10:24.296] [1/4] Resolving packages...
[10:10:31.436] [2/4] Fetching packages...
[10:10:40.886] [3/4] Linking dependencies...
[10:10:40.889] warning " > eslint-config-next@12.3.4" has unmet peer dependency "eslint@^7.23.0 || ^8.0.0".
[10:10:40.889] warning "eslint-config-next > eslint-plugin-import@2.26.0" has unmet peer dependency "eslint@^2 || ^3 || ^4 || ^5 || ^6 || ^7.2.0 || ^8".
[10:10:40.890] warning "eslint-config-next > eslint-import-resolver-typescript@2.7.1" has unmet peer dependency "eslint@*".
[10:10:40.890] warning "eslint-config-next > eslint-plugin-react@7.31.11" has unmet peer dependency "eslint@^3 || ^4 || ^5 || ^6 || ^7 || ^8".
[10:10:40.890] warning "eslint-config-next > eslint-plugin-jsx-a11y@6.6.1" has unmet peer dependency "eslint@^3 || ^4 || ^5 || ^6 || ^7 || ^8".
[10:10:40.890] warning "eslint-config-next > @typescript-eslint/parser@5.44.0" has unmet peer dependency "eslint@^6.0.0 || ^7.0.0 || ^8.0.0".
[10:10:40.890] warning "eslint-config-next > eslint-plugin-react-hooks@4.6.0" has unmet peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0 || ^8.0.0-0".
[10:10:45.683] [4/4] Building fresh packages...
[10:10:46.012] success Saved lockfile.
[10:10:46.016] Done in 21.75s.
[10:10:46.052] Detected Next.js version: 12.3.4
[10:10:46.053] Running "yarn run build"
[10:10:46.326] yarn run v1.22.17
[10:10:46.349] $ next build
[10:10:46.769] warn  - Invalid next.config.js options detected: 
[10:10:46.771]   - The value at .images.domains[0] must be a string but it was undefined.
[10:10:46.772] 
[10:10:46.772] See more info here: https://nextjs.org/docs/messages/invalid-next-config
[10:10:46.775] 
[10:10:46.775] > Build error occurred
[10:10:46.777] Error: Specified images.domains should be an Array of strings received invalid values ().
[10:10:46.777] See more info here: https://nextjs.org/docs/messages/invalid-images-config
[10:10:46.777]     at assignDefaults (/vercel/path0/node_modules/next/dist/server/config.js:326:23)
[10:10:46.777]     at Object.loadConfig [as default] (/vercel/path0/node_modules/next/dist/server/config.js:105:16)
[10:10:46.777]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
[10:10:46.777]     at async /vercel/path0/node_modules/next/dist/build/index.js:69:28
[10:10:46.777]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
[10:10:46.777]     at async Object.build [as default] (/vercel/path0/node_modules/next/dist/build/index.js:65:29)
[10:10:46.794] error Command failed with exit code 1.
[10:10:46.794] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[10:10:46.815] Error: Command "yarn run build" exited with 1
```

**Comment by shadcn** [comment]
@engageintellect You need to add the environment variables to connect your Next.js site to your Drupal site. See https://next-drupal.org/docs/environment-variables

When deploying to Vercel, you need to add the variables in your project settings.

<img width="636" alt="rdgj0cgX" src="https://user-images.githubusercontent.com/124599/204324466-78c18110-4e35-4de5-9226-92fadad3f03a.png">
