### ISSUE TITLE
TypeError: Cannot read property 'some' of undefined

### ISSUE THREAD

**Issue by sybercoda** [chapter-three/next-drupal#4]
Any assistance on why 'some' is undefined? 

TypeError: Cannot read property 'some' of undefined
    at filter (webpack-internal:///./pages/index.tsx:71:41)
    at Array.filter (<anonymous>)
    at /Sites/next-drupal/examples/example-blog/node_modules/next-drupal/dist/index.js:124:29
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async getStaticProps (webpack-internal:///./pages/index.tsx:66:20)
    at async renderToHTML (/Sites/next-drupal/examples/example-blog/node_modules/next/dist/next-server/server/render.js:28:1780)
    at async /Sites/next-drupal/examples/example-blog/node_modules/next/dist/next-server/server/next-server.js:112:97
    at async __wrapper (/Sites/next-drupal/examples/example-blog/node_modules/next/dist/lib/coalesced-function.js:1:330)

**Comment by arshad** [comment]
Can you share the code snippet where you're using `some`? Thanks.

**Comment by sybercoda** [comment]
Line #79 on the [...slug].tsx file linked below.
https://github.com/arshad/next-drupal/blob/master/examples/example-blog/pages/blog/%5B...slug%5D.tsx

Note that it's a type error, as shown below. My guess is that "getEntityFromContext", which is using JSON.parse, is returning entity as an object but entity should be an array to use some() method.  

TypeError: _entity$field_site.some is not a function
    at filter (webpack-internal:///./pages/blog/[...slug].tsx:170:127)
    at Array.filter (<anonymous>)
    at /Sites/next-drupal/examples/example-blog/node_modules/next-drupal/dist/index.js:269:29
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async getStaticPaths (webpack-internal:///./pages/blog/[...slug].tsx:163:17)
    at async buildStaticPaths (/Sites/next-drupal/examples/example-blog/node_modules/next/dist/build/utils.js:16:80) {
  type: 'TypeError'
}

**Comment by arshad** [comment]
This code is outdated now. We've updated the API in the recent releases. Marking this is closed. Thank you.
