### ISSUE TITLE
Error: Failed prop type: The prop `href` expects a `string` or `object` in `<Link>`, but got `null` instead.

### ISSUE THREAD

**Issue by 2dareis2do** [chapter-three/next-drupal#469]
I have just done a fresh install of the Unami demo doing a fresh install as shown here:

https://next-drupal.org/guides/umami-demo

On thing I noticed is that the patch for drupal/decoupled_router looks like it is out of date, at least it is a different version to the one shown here:

https://next-drupal.org/learn/quick-start/apply-patches

Also as i have set up  the umami.demo on a self signed certificate I had to add NODE_TLS_REJECT_UNAUTHORIZED = "0"
to my .env.local file.

Any way when launching localhost running npm run dev I get the following error?

error - node_modules/next/dist/client/link.js (75:19) @ createPropError
error - Error: Failed prop type: The prop `href` expects a `string` or `object` in `<Link>`, but got `null` instead.
    at createPropError (webpack-internal:///./node_modules/next/dist/client/link.js:75:20)
    at eval (webpack-internal:///./node_modules/next/dist/client/link.js:85:27)
    at Array.forEach (<anonymous>)

The odd thing this was kind of working previously on loading the home page, but threw this error when navigating to a sub page. Now the home page does not seem to work either?

**Comment by kopeboy** [comment]
I'm receiving the same error when trying to use Nextjs on a local Drupal site in a DDEV container.

Your suggestion (with hostname '[my-project-name].ddev.site') won't fix it.
