### ISSUE TITLE
Unauthorized on when using preview

### ISSUE THREAD

**Issue by arborgwebadmin** [chapter-three/next-drupal#8]
I first want to start by thanking you for an amazing job on this module. 
I'm getting an error when I set DRUPAL_CLIENT_ID, DRUPAL_CLIENT_SECRET and  DRUPAL_PREVIEW_SECRET. 

`{ Error: Unauthorized
    at /home/superhetja/next/fristundir/node_modules/next-drupal/dist/index.js:24:15
    at process._tickCallback (internal/process/next_tick.js:68:7) type: 'Error' }`

The Error doesn't tell me a lot and I have tried debugging it without luck. The access log on the drupal server doesn't tell me a lot either 
`"POST /oauth/token HTTP/1.1" 401 5377 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
"POST /oauth/token HTTP/1.1" 401 788 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"`
I don't know if I'm forgetting something in the oauth configuration or what could be wrong. 
I'm Drupal version 9.2.0 on Apache with php 7.4.3

**Comment by arshad** [comment]
OK let's see. Can you verify if the DRUPAL_CLIENT_ID and DRUPAL_CLIENT_SECRET are correct?

Is this happening on preview only (i.e when you access a node from the Drupal admin)? Does it fail with the same error when you visit a page on the Next.js site?
